# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeRandomSelection <- function(dist, requiredN, preselected, seed) {
    .Call('_coreCollection_computeRandomSelection', PACKAGE = 'coreCollection', dist, requiredN, preselected, seed)
}

computeAdjustedSelectionUsingRecomputeMethod <- function(dist, adjustedSelected) {
    .Call('_coreCollection_computeAdjustedSelectionUsingRecomputeMethod', PACKAGE = 'coreCollection', dist, adjustedSelected)
}

computeAdjustedSelectionUsingSplitMethod <- function(dist, groups, preselected) {
    .Call('_coreCollection_computeAdjustedSelectionUsingSplitMethod', PACKAGE = 'coreCollection', dist, groups, preselected)
}

computeCore <- function(algorithm, method, dist, groups) {
    .Call('_coreCollection_computeCore', PACKAGE = 'coreCollection', algorithm, method, dist, groups)
}

computeMeasure <- function(method, dist, c) {
    .Call('_coreCollection_computeMeasure', PACKAGE = 'coreCollection', method, dist, c)
}

