# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeRandomSelection <- function(dist, requiredN, preselected) {
    .Call('_coreCollection_computeRandomSelection', PACKAGE = 'coreCollection', dist, requiredN, preselected)
}

computeAdjustedSelectionUsingRecomputeMethod <- function(dist, adjustedSelected) {
    .Call('_coreCollection_computeAdjustedSelectionUsingRecomputeMethod', PACKAGE = 'coreCollection', dist, adjustedSelected)
}

computeAdjustedSelectionUsingSplitMethod <- function(dist, groups, preselected) {
    .Call('_coreCollection_computeAdjustedSelectionUsingSplitMethod', PACKAGE = 'coreCollection', dist, groups, preselected)
}

computeCore <- function(method, dist, groups) {
    .Call('_coreCollection_computeCore', PACKAGE = 'coreCollection', method, dist, groups)
}

computeDistance <- function(method, dist, entries) {
    .Call('_coreCollection_computeDistance', PACKAGE = 'coreCollection', method, dist, entries)
}

